cart_show:
    path: /
    controller: App\Controller\CartController::showAction
    methods: [GET]

cart_add:
    path: /add/{id}
    controller: App\Controller\CartController::addAction
    methods: [GET, POST]

cart_update:
    path: /update/{id}/{quantity}
    controller: App\Controller\CartController::updateAction
    methods: [GET, POST]

cart_remove:
    path: /remove/{id}
    controller: App\Controller\CartController::removeAction
    methods: [DELETE]