catalog_index:
    path: /
    controller: App\Controller\CatalogController::indexAction
    methods: [GET, POST]

catalog_show:
    path: /{id}-{slug}
    controller: App\Controller\CatalogController::showAction
    methods: [GET]