category_index:
    path: /
    controller: App\Controller\CategoryController::indexAction
    methods: [GET]

category_new:
    path: /new
    controller: App\Controller\CategoryController::newAction
    methods: [GET, POST]

category_show:
    path: /{id}
    controller: App\Controller\CategoryController::showAction
    methods: [GET]

category_edit:
    path: /{id}/edit
    controller: App\Controller\CategoryController::editAction
    methods: [GET, POST]

category_delete:
    path: /{id}
    controller: App\Controller\CategoryController::deleteAction
    methods: [DELETE]