checkout_address:
    path: /address
    controller: App\Controller\CheckoutController::addressAction
    methods: [GET, POST]

checkout_summary:
    path: /summary
    controller: App\Controller\CheckoutController::summaryAction
    methods: [GET, POST]

checkout_confirm:
    path: /confirm
    controller: App\Controller\CheckoutController::confirmAction
    methods: [GET, POST]

checkout_success:
    path: /success
    controller: App\Controller\CheckoutController::successAction
    methods: [GET, POST]