product_index:
    path: /
    controller: App\Controller\ProductController::indexAction
    methods: [GET, POST]

product_new:
    path: /new
    controller: App\Controller\ProductController::newAction
    methods: [GET, POST]

product_show:
    path: /{id}-{slug}
    controller: App\Controller\ProductController::showAction
    methods: [GET]

product_edit:
    path: /{id}/edit
    controller: App\Controller\ProductController::editAction
    methods: [GET, POST]

product_delete:
    path: /{id}
    controller: App\Controller\ProductController::deleteAction
    methods: [DELETE]