app_register:
    path: /register
    controller: App\Controller\RegistrationController::registerAction

app_login:
    path: /login
    controller: App\Controller\SecurityController::loginAction

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logoutAction

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::editProfileAction

app_customer_profile:
    path: /customer-profile
    controller: App\Controller\CustomerProfileController::editAction

app_forgot_password:
    path: /forgot-password
    controller: App\Controller\ResetPasswordController::forgotPasswordAction
    methods: [GET, POST]

app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ResetPasswordController::resetPasswordAction
    methods: [GET, POST]
    requirements:
        token: '[a-f0-9]{64}'