app_register:
    path: /register
    controller: App\Controller\RegistrationController::registerAction

app_login:
    path: /login
    controller: App\Controller\SecurityController::loginAction

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logoutAction

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::editProfileAction

app_customer_profile:
    path: /customer-profile
    controller: App\Controller\CustomerProfileController::editAction