App\Form\ForgotPasswordType:
    properties:
        email:
            - NotBlank:
                message: "Please enter your email address."
            - Email:
                message: "Please enter a valid email address."