App\Form\ResetPasswordType:
    properties:
        # password:
        #     - NotBlank:
        #         message: "Please enter a new password."
        #     - Length:
        #         min: 8
        #         minMessage: "Your password must be at least {{ limit }} characters long."
        #     - Regex:
        #         pattern: '^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$'
        #         message: "Your password must contain at least one letter and one number."