#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_routes:
    resource: "routes/user.yaml"
    type: "yaml"

product_routes:
    resource: "routes/product.yaml"
    type: "yaml"

category_routes:
    resource: "routes/category.yaml"
    type: "yaml"

catalog_routes:
    resource: "routes/catalog.yaml"
    type: "yaml"