homepage:
   path: /
   controller: App\Controller\DefaultController::homepageAction

user_routes:
    resource: "routes/user.yaml"
    type: "yaml"

product_routes:
    resource: "routes/product.yaml"
    type: "yaml"

category_routes:
    resource: "routes/category.yaml"
    type: "yaml"

catalog_routes:
    resource: "routes/catalog.yaml"
    type: "yaml"

cart_routes:
    resource: "routes/cart.yaml"
    type: "yaml"